DELETE http://localhost:8000/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWFkbWFtZWVuQGdtYWlsLmNvbSIsImV4cCI6MTc3MDgzNzc1MiwidXNlcklkIjoyfQ.fozI9BGKhwx2E2CYwUycOZkehypieEJ53g_ZYruIzZ4
