DELETE http://localhost:8000/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWFkLmFtZWVuQGdtYWlsLmNvbSIsImV4cCI6MTc3MDgzNTQ3NSwidXNlcklkIjoxfQ.nUQT32vMZNlHX7Ls7vWihc4Ed_J89hg3QzmXuXrvl9E