GET http://localhost:8000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWFkbWFtZWVuQGdtYWlsLmNvbSIsImV4cCI6MTc3MDgzNDk5MCwidXNlcklkIjoyfQ.WG8TT-7Zo7Zrvqt1hI0TASNfBUKo_jIM0H3SK4rhjOc
