GET http://localhost:8000/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWFkbWFtZWVuQGdtYWlsLmNvbSIsImV4cCI6MTc3MDkyMDk5NCwidXNlcklkIjoyfQ.pRzmnnvwKMB-jMCPeewMhTIomVxsWTo7Gjh3Rm-6fYc
