// Code generated by MockGen. DO NOT EDIT.
// Source: services/register.go
//
// Generated by this command:
//
//	mockgen -source=services/register.go -destination=services/mocks/mock_register_repository.go -package=mocks RegisterRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "event-booking/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegisterRepository is a mock of RegisterRepository interface.
type MockRegisterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterRepositoryMockRecorder
	isgomock struct{}
}

// MockRegisterRepositoryMockRecorder is the mock recorder for MockRegisterRepository.
type MockRegisterRepositoryMockRecorder struct {
	mock *MockRegisterRepository
}

// NewMockRegisterRepository creates a new mock instance.
func NewMockRegisterRepository(ctrl *gomock.Controller) *MockRegisterRepository {
	mock := &MockRegisterRepository{ctrl: ctrl}
	mock.recorder = &MockRegisterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterRepository) EXPECT() *MockRegisterRepositoryMockRecorder {
	return m.recorder
}

// DeleteRegisteredEvent mocks base method.
func (m *MockRegisterRepository) DeleteRegisteredEvent(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegisteredEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegisteredEvent indicates an expected call of DeleteRegisteredEvent.
func (mr *MockRegisterRepositoryMockRecorder) DeleteRegisteredEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegisteredEvent", reflect.TypeOf((*MockRegisterRepository)(nil).DeleteRegisteredEvent), arg0)
}

// GetEventById mocks base method.
func (m *MockRegisterRepository) GetEventById(arg0 int64) (models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventById", arg0)
	ret0, _ := ret[0].(models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventById indicates an expected call of GetEventById.
func (mr *MockRegisterRepositoryMockRecorder) GetEventById(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventById", reflect.TypeOf((*MockRegisterRepository)(nil).GetEventById), arg0)
}

// GetRegisteredEventById mocks base method.
func (m *MockRegisterRepository) GetRegisteredEventById(arg0, arg1 int64) (models.RegisterEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredEventById", arg0, arg1)
	ret0, _ := ret[0].(models.RegisterEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredEventById indicates an expected call of GetRegisteredEventById.
func (mr *MockRegisterRepositoryMockRecorder) GetRegisteredEventById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredEventById", reflect.TypeOf((*MockRegisterRepository)(nil).GetRegisteredEventById), arg0, arg1)
}

// RegisterEvent mocks base method.
func (m *MockRegisterRepository) RegisterEvent(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterEvent indicates an expected call of RegisterEvent.
func (mr *MockRegisterRepositoryMockRecorder) RegisterEvent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEvent", reflect.TypeOf((*MockRegisterRepository)(nil).RegisterEvent), arg0, arg1)
}
